#!/bin/bash
#
# Provides a list of commit messages between 
# Copyright (c) 2019, Roozbeh Farahbod
#

RANGE="$1"
EXECUTABLE=`basename $0`

if [ -z "$RANGE" ]
then
    echo "Error: range is not provided."
    echo "Usage: $EXECUTABLE <range>"
    echo "Example: $EXECUTABLE v1.2.0..develop-v1.3"
    exit 1
fi

git log "$RANGE" | egrep "^(    )|(commit)" | sed 's/^commit.*$/*/'


