#!/bin/bash
#
# Opens the Web page of the current git workspace. 
#
# Copyright (c) 2018-2019, Roozbeh Farahbod
#

if [ -z "$1" ]
then
  REPO_SED="s/^git@\(.*\):\(.*\)\.git/https:\/\/\1\/\2/g"
else
  REPO_SED="$1"
fi

URL=$(git remote -v | grep fetch | awk '{print $2}' | sed "${REPO_SED}") 

if [[ $URL == "https"* ]]
then
  echo $URL
else
  echo "Sorry, this script does not support HTTPS repository URLs."
fi

osopen $URL

