#!/bin/bash

TECH="$1"

if [ -z "${TECH}" ]
then
    echo "Usage: git ignore <tech>"
    echo "Examples of tech: Go, Node, Python, Lua"
    exit 1
fi

if [ ! -e ".gitignore" ]; then \
    curl -q https://raw.githubusercontent.com/github/gitignore/master/${TECH}.gitignore > .gitignore; \
    echo "\n/bin" >> .gitignore; \
    echo "'.gitignore' downloaded."; \
else \
    echo "Did not change '.gitignore'."; \
fi
